#!/usr/bin/env python3
"""Run a non-science smoke test for the dissolution pipeline.

The rows below are generated by jittering the few preview rows visible in the
PDF appendix. They are only for exercising the code path and are written under
``/private/tmp`` by default.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pandas as pd


def build_smoke_catalog(path: Path) -> None:
    cols = [
        "pair_id",
        "cluster1",
        "cluster2",
        "log_age1",
        "log_age2",
        "mass1",
        "mass2",
        "separation_pc",
        "vesc_kms",
        "vrel_kms",
        "tf1",
        "tf2",
        "ra1_deg",
        "dec1_deg",
        "parallax1_mas",
        "pmra1_masyr",
        "pmdec1_masyr",
        "rv1_kms",
        "ra2_deg",
        "dec2_deg",
        "parallax2_mas",
        "pmra2_masyr",
        "pmdec2_masyr",
        "rv2_kms",
    ]
    preview = [
        (1, "ASCC 21", "Briceno 1", 6.95, 7.05, 84.01, 159.65, 13.29, 0.39, 6.66, 7.56, 11.57, 82.35, 3.43, 2.91, 1.49, -0.56, 9.52, 81.12, 1.56, 2.88, 1.39, -0.06, 16.13),
        (2, "HSC 1071", "Stock 5", 7.45, 7.85, 57.47, 278.28, 14.71, 0.44, 9.82, 1.81, 28.55, 33.44, 64.34, 1.02, -0.70, -2.20, -20.49, 31.13, 64.37, 1.04, -0.81, -2.19, -25.99),
        (3, "HSC 2893", "UFMG 24", 8.05, 8.80, 40.28, 58.94, 14.43, 0.24, 3.54, 19.46, 48.74, 258.18, -36.48, 0.69, 2.09, -1.35, -21.53, 258.00, -35.94, 0.71, 1.94, -1.04, -22.49),
        (81, "HSC 1370", "Theia 669", 7.80, 8.15, 45.45, 46.47, 199.72, 0.06, 24.09, 58521.01, 48037.05, 95.25, 38.42, 0.94, 1.82, -3.15, -32.91, 91.56, 38.83, 1.11, 1.62, -3.09, -9.52),
        (83, "CWNU 158", "Gulliver 32", 8.95, 9.40, 124.34, 84.55, 189.63, 0.09, 8.56, 19865.69, 28171.25, 99.99, 5.21, 0.63, -1.39, 2.90, 40.72, 98.38, 7.51, 0.55, -0.92, 2.23, 46.49),
    ]
    rows = []
    for rep in range(4):
        for row in preview:
            item = list(row)
            item[0] = row[0] + 100 * rep
            item[3] = row[3] + 0.03 * rep
            item[4] = row[4] + 0.03 * rep
            item[7] = row[7] * (1 + 0.02 * rep)
            item[8] = row[8] * (1 + 0.05 * rep)
            item[9] = row[9] * (1 + 0.04 * rep)
            rows.append(item)
    path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows, columns=cols).to_csv(path, index=False)


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    tmp = Path("/private/tmp/binary_cluster_dissolution_smoke")
    catalog = tmp / "smoke_catalog.csv"
    build_smoke_catalog(catalog)
    cmd = [
        sys.executable,
        str(repo / "scripts" / "binary_cluster_dissolution.py"),
        "--catalog",
        str(catalog),
        "--bootstrap",
        "25",
    ]
    subprocess.run(cmd, cwd=tmp, check=True)
    print(f"Smoke outputs written under {tmp / 'results'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
